DROP TABLE "PRODUTO";
CREATE TABLE   "PRODUTO"(
    "ID_PRODUTO" INTEGER PRIMARY KEY,
    "DESC_PRODUTO" VARCHAR2(100),
    "VALOR_PRODUTO" NUMBER
);


INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (1, 'Cereal Matinal 500g', 10.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (2, 'Carne Bovina 1Kg', 25.49);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (3, 'Leite UHT 1L', 5.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (4, 'Café 1Kg', 15.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (5, 'Manteiga 500g', 8.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (6, 'Carne de Frango', 19.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (7, 'Requeijão 1Kg', 12.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (8, 'Cebola 1Kg', 7.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (9, 'Laranja Pera 1Kg', 14.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (10, 'Coca-Cola 2L', 9.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (11, 'Agua de Coco 1L', 12.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (12, 'Maçã Gala 1Kg', 6.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (13, 'Melão UND', 17.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (14, 'Lasanha Congelada 600g', 22.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (15, 'Pizza Congelada 500g', 14.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (16, 'Mamão 1Kg', 8.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (17, 'Cartela de Ovos (12 Und)', 11.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (18, 'Presunto 1Kg', 19.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (19, 'Batata Palha 400g', 5.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (20, 'Maionese 500g', 10.00);


--SELECT * FROM "PRODUTO";